apiVersion: v1
kind: Namespace
metadata:
  name: aks-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: aks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: <userid>.dkr.ecr.ap-east-1.amazonaws.com/demo/ecr:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: aks-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: http-server